on: push
name: Tests
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: run CI
      uses: cedrickring/golang-action@1.6.0
      with:
        args: make install-ci-deps && make install-packages && make checker && make run-tests
      env:
        GO111MODULE: "on"       

       
      